apiVersion: apps/v1
kind: Deployment
metadata:
  name: calangoui-docs
spec:
  template:
    spec:
      containers:
        - name: app
          image: ghcr.io/by2-studio/calangoui-docs:4a02ac32939f2e606fc17de8b1b52caa1698075b
