apiVersion: apps/v1
kind: Deployment
metadata:
  name: calangoui-docs
spec:
  template:
    spec:
      containers:
        - name: app
          image: ghcr.io/by2-studio/calangoui-docs:552f9b45b47a5a38d75c8a8a9ff8e66ea795d131
