apiVersion: apps/v1
kind: Deployment
metadata:
  name: calangoui-docs
spec:
  template:
    spec:
      containers:
        - name: app
          image: ghcr.io/by2-studio/calangoui-docs:3300b29e4ed5524a6296aa0c0b6e6316ef99d262
