apiVersion: apps/v1
kind: Deployment
metadata:
  name: calangoui-mcp
spec:
  template:
    spec:
      containers:
        - name: app
          image: ghcr.io/by2-studio/calangoui-mcp:76dea73d2ab3911ea6c05e1d9f0c8c077e48dc9b
