apiVersion: apps/v1
kind: Deployment
metadata:
  name: calangoui-mcp
spec:
  template:
    spec:
      containers:
        - name: app
          image: ghcr.io/by2-studio/calangoui-mcp:9dadcc2751ad9c06a3240e64be86d414f40c9a4f
